# Generated by Django 4.2.2 on 2023-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_alter_datas_sl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Description',
            field=models.TextField(max_length=300),
        ),
    ]
